import type { Check, Claim, Evidence } from "@shared/types";
import jsPDF from "jspdf";

interface ExportOptions {
  format: 'pdf' | 'json' | 'markdown';
  includeEvidence?: boolean;
  includeMetadata?: boolean;
}

/**
 * Export check results in various formats
 */
export class ExportService {
  /**
   * Export check results based on format
   */
  static async exportCheck(check: Check, options: ExportOptions): Promise<void> {
    switch (options.format) {
      case 'pdf':
        return this.exportAsPDF(check, options);
      case 'json':
        return this.exportAsJSON(check, options);
      case 'markdown':
        return this.exportAsMarkdown(check, options);
      default:
        throw new Error(`Unsupported export format: ${options.format}`);
    }
  }

  /**
   * Export as PDF document
   */
  private static async exportAsPDF(check: Check, options: ExportOptions): Promise<void> {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    let yPosition = margin;

    // Title
    pdf.setFontSize(20);
    pdf.setFont("helvetica", "bold");
    pdf.text("Fact-Check Report", margin, yPosition);
    yPosition += 15;

    // Generated by Tru8
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(100);
    pdf.text("Generated by Tru8 - Instant Fact Checking", margin, yPosition);
    yPosition += 10;

    // Date
    pdf.text(new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }), margin, yPosition);
    yPosition += 15;

    // Reset text color
    pdf.setTextColor(0);

    // Check Details
    if (options.includeMetadata) {
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Check Details", margin, yPosition);
      yPosition += 10;

      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      
      if (check.inputUrl) {
        pdf.text(`Source: ${check.inputUrl}`, margin, yPosition);
        yPosition += 7;
      }
      
      pdf.text(`Input Type: ${check.inputType}`, margin, yPosition);
      yPosition += 7;
      
      pdf.text(`Credits Used: ${check.creditsUsed}`, margin, yPosition);
      yPosition += 7;
      
      if (check.processingTimeMs) {
        pdf.text(`Processing Time: ${(check.processingTimeMs / 1000).toFixed(1)}s`, margin, yPosition);
        yPosition += 7;
      }
      
      yPosition += 10;
    }

    // Claims
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Claims Analysis", margin, yPosition);
    yPosition += 10;

    if (check.claims) {
      check.claims.forEach((claim, index) => {
        // Check if we need a new page
        if (yPosition > pageHeight - 50) {
          pdf.addPage();
          yPosition = margin;
        }

        // Claim header
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text(`Claim ${index + 1}: ${claim.verdict.toUpperCase()}`, margin, yPosition);
        yPosition += 7;

        // Claim text
        pdf.setFontSize(10);
        pdf.setFont("helvetica", "normal");
        const claimLines = pdf.splitTextToSize(claim.text, pageWidth - 2 * margin);
        claimLines.forEach((line: string) => {
          if (yPosition > pageHeight - 20) {
            pdf.addPage();
            yPosition = margin;
          }
          pdf.text(line, margin, yPosition);
          yPosition += 5;
        });
        yPosition += 3;

        // Confidence
        pdf.text(`Confidence: ${Math.round(claim.confidence)}%`, margin, yPosition);
        yPosition += 7;

        // Rationale
        pdf.setFont("helvetica", "italic");
        const rationaleLines = pdf.splitTextToSize(claim.rationale, pageWidth - 2 * margin);
        rationaleLines.forEach((line: string) => {
          if (yPosition > pageHeight - 20) {
            pdf.addPage();
            yPosition = margin;
          }
          pdf.text(line, margin, yPosition);
          yPosition += 5;
        });
        pdf.setFont("helvetica", "normal");
        yPosition += 5;

        // Evidence
        if (options.includeEvidence && claim.evidence) {
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "bold");
          pdf.text("Sources:", margin + 5, yPosition);
          yPosition += 7;
          pdf.setFont("helvetica", "normal");

          claim.evidence.slice(0, 3).forEach((ev) => {
            if (yPosition > pageHeight - 20) {
              pdf.addPage();
              yPosition = margin;
            }
            pdf.setFontSize(9);
            pdf.text(`• ${ev.source} - ${ev.title}`, margin + 10, yPosition);
            yPosition += 5;
          });
        }

        yPosition += 10;
      });
    }

    // Save the PDF
    const filename = `fact-check-${check.id}-${Date.now()}.pdf`;
    pdf.save(filename);
  }

  /**
   * Export as JSON
   */
  private static async exportAsJSON(check: Check, options: ExportOptions): Promise<void> {
    const exportData = {
      ...check,
      exportedAt: new Date().toISOString(),
      exportVersion: "1.0",
    };

    if (!options.includeEvidence && exportData.claims) {
      exportData.claims = exportData.claims.map(claim => {
        const { evidence, ...claimWithoutEvidence } = claim;
        return {
          ...claimWithoutEvidence,
          evidence: [] // Provide empty array instead of undefined
        };
      });
    }

    if (!options.includeMetadata) {
      delete (exportData as any).createdAt;
      delete (exportData as any).completedAt;
      delete (exportData as any).processingTimeMs;
    }

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { 
      type: 'application/json' 
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fact-check-${check.id}-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Export as Markdown
   */
  private static async exportAsMarkdown(check: Check, options: ExportOptions): Promise<void> {
    let markdown = `# Fact-Check Report\n\n`;
    markdown += `*Generated by Tru8 - ${new Date().toLocaleDateString()}*\n\n`;

    if (options.includeMetadata) {
      markdown += `## Check Details\n\n`;
      if (check.inputUrl) {
        markdown += `- **Source:** ${check.inputUrl}\n`;
      }
      markdown += `- **Input Type:** ${check.inputType}\n`;
      markdown += `- **Credits Used:** ${check.creditsUsed}\n`;
      if (check.processingTimeMs) {
        markdown += `- **Processing Time:** ${(check.processingTimeMs / 1000).toFixed(1)}s\n`;
      }
      markdown += `\n`;
    }

    markdown += `## Claims Analysis\n\n`;

    if (check.claims) {
      check.claims.forEach((claim, index) => {
        markdown += `### Claim ${index + 1}\n\n`;
        markdown += `**Verdict:** ${claim.verdict.toUpperCase()} (${Math.round(claim.confidence)}% confidence)\n\n`;
        markdown += `> ${claim.text}\n\n`;
        markdown += `**Analysis:** ${claim.rationale}\n\n`;

        if (options.includeEvidence && claim.evidence && claim.evidence.length > 0) {
          markdown += `**Sources:**\n\n`;
          claim.evidence.forEach((ev) => {
            markdown += `- [${ev.source}](${ev.url}) - ${ev.title}`;
            if (ev.publishedDate) {
              markdown += ` (${new Date(ev.publishedDate).toLocaleDateString()})`;
            }
            markdown += `\n`;
            if (ev.snippet) {
              markdown += `  > ${ev.snippet.substring(0, 200)}...\n`;
            }
          });
          markdown += `\n`;
        }
      });
    }

    markdown += `---\n\n`;
    markdown += `*This report was automatically generated by [Tru8](https://tru8.app)*\n`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fact-check-${check.id}-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}