"""Add PDF citation and NLI context fields to Evidence table

Revision ID: 954dd02c2ec1
Revises: 871f08e9f196
Create Date: 2025-10-29 17:11:35.250654+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '954dd02c2ec1'
down_revision: Union[str, None] = '871f08e9f196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('check', 'overall_summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('check', 'claims_supported',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('check', 'claims_contradicted',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('check', 'claims_uncertain',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('claim', 'abstention_reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # Phase 2: Add new PDF citation and NLI context columns
    op.add_column('evidence', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('evidence', sa.Column('context_before', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('context_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('nli_stance', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('nli_confidence', sa.Float(), nullable=True))
    op.add_column('evidence', sa.Column('nli_entailment', sa.Float(), nullable=True))
    op.add_column('evidence', sa.Column('nli_contradiction', sa.Float(), nullable=True))

    # Fix existing NULL credibility_score values before setting NOT NULL constraint
    op.execute("UPDATE evidence SET credibility_score = 0.6 WHERE credibility_score IS NULL")
    op.alter_column('evidence', 'credibility_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('evidence', 'tier',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('evidence', 'credibility_reasoning',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('evidence', 'risk_level',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('evidence', 'risk_warning',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence', 'risk_warning',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('evidence', 'risk_level',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('evidence', 'credibility_reasoning',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('evidence', 'tier',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('evidence', 'credibility_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('evidence', 'nli_contradiction')
    op.drop_column('evidence', 'nli_entailment')
    op.drop_column('evidence', 'nli_confidence')
    op.drop_column('evidence', 'nli_stance')
    op.drop_column('evidence', 'context_after')
    op.drop_column('evidence', 'context_before')
    op.drop_column('evidence', 'page_number')
    op.alter_column('claim', 'abstention_reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('check', 'claims_uncertain',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('check', 'claims_contradicted',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('check', 'claims_supported',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('check', 'overall_summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###