"""Add legal_metadata field to claims

Revision ID: f53f987eedde
Revises: ce31cca719e1
Create Date: 2025-11-11 13:25:53.757375+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53f987eedde'
down_revision: Union[str, None] = 'ce31cca719e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('legal_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'legal_metadata')
    # ### end Alembic commands ###