"""Add pipeline improvement fields (Phase 1-2)

Revision ID: 06b51a7c2d88
Revises: edbbfe4c0ea9
Create Date: 2025-10-20 13:55:24.530768+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '06b51a7c2d88'
down_revision: Union[str, None] = 'edbbfe4c0ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('decision_trail', sa.JSON(), nullable=True))
    op.add_column('check', sa.Column('transparency_score', sa.Float(), nullable=True))
    op.add_column('claim', sa.Column('temporal_markers', sa.JSON(), nullable=True))
    op.add_column('claim', sa.Column('time_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('claim', sa.Column('is_time_sensitive', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('claim', sa.Column('claim_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('claim', sa.Column('is_verifiable', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('claim', sa.Column('verifiability_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('claim', sa.Column('uncertainty_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('claim', sa.Column('confidence_breakdown', sa.JSON(), nullable=True))
    op.add_column('evidence', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('is_syndicated', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('evidence', sa.Column('original_source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('parent_company', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('independence_flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('domain_cluster_id', sa.Integer(), nullable=True))
    op.add_column('evidence', sa.Column('is_factcheck', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('evidence', sa.Column('factcheck_publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('factcheck_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('factcheck_date', sa.DateTime(), nullable=True))
    op.add_column('evidence', sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('temporal_relevance_score', sa.Float(), nullable=True))
    op.add_column('evidence', sa.Column('extracted_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evidence', sa.Column('is_time_sensitive', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('evidence', sa.Column('temporal_window', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # Removed credibility_score alter - unrelated to pipeline improvements and has data integrity issues
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence', 'credibility_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('evidence', 'temporal_window')
    op.drop_column('evidence', 'is_time_sensitive')
    op.drop_column('evidence', 'extracted_date')
    op.drop_column('evidence', 'temporal_relevance_score')
    op.drop_column('evidence', 'source_type')
    op.drop_column('evidence', 'factcheck_date')
    op.drop_column('evidence', 'factcheck_rating')
    op.drop_column('evidence', 'factcheck_publisher')
    op.drop_column('evidence', 'is_factcheck')
    op.drop_column('evidence', 'domain_cluster_id')
    op.drop_column('evidence', 'independence_flag')
    op.drop_column('evidence', 'parent_company')
    op.drop_column('evidence', 'original_source_url')
    op.drop_column('evidence', 'is_syndicated')
    op.drop_column('evidence', 'content_hash')
    op.drop_column('claim', 'confidence_breakdown')
    op.drop_column('claim', 'uncertainty_explanation')
    op.drop_column('claim', 'verifiability_reason')
    op.drop_column('claim', 'is_verifiable')
    op.drop_column('claim', 'claim_type')
    op.drop_column('claim', 'is_time_sensitive')
    op.drop_column('claim', 'time_reference')
    op.drop_column('claim', 'temporal_markers')
    op.drop_column('check', 'transparency_score')
    op.drop_column('check', 'decision_trail')
    # ### end Alembic commands ###