"""Add stripe_customer_id to subscription

Revision ID: edbbfe4c0ea9
Revises: 
Create Date: 2025-10-15 13:48:23.334212+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbbfe4c0ea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add stripe_customer_id column - removed credibility_score change
    op.add_column('subscription', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove stripe_customer_id column
    op.drop_column('subscription', 'stripe_customer_id')
    # ### end Alembic commands ###