"""add_current_verified_data_to_claim

Revision ID: 12c6bf45de11
Revises: add_article_classification
Create Date: 2025-12-02 15:49:05.699313+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12c6bf45de11'
down_revision: Union[str, None] = 'add_article_classification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('current_verified_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('claim', 'source_date',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Publication date of source article',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim', 'source_date',
               existing_type=sa.VARCHAR(),
               comment='Publication date of source article',
               existing_nullable=True)
    op.drop_column('claim', 'current_verified_data')
    # ### end Alembic commands ###