"""add_article_excerpt_field_to_check

Revision ID: c78bee2049c5
Revises: tier1_primary_source
Create Date: 2025-11-19 11:18:05.946887+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c78bee2049c5'
down_revision: Union[str, None] = 'tier1_primary_source'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check', sa.Column('article_excerpt', sa.String(length=5000), nullable=True))
    op.alter_column('check', 'api_coverage_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('evidence', 'is_primary_source',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='True if evidence is original research, government data, or official report',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('evidence', 'primary_indicators',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON array of primary source indicators detected (e.g., ["academic_journal", "peer_reviewed"])',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evidence', 'primary_indicators',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON array of primary source indicators detected (e.g., ["academic_journal", "peer_reviewed"])',
               existing_nullable=True)
    op.alter_column('evidence', 'is_primary_source',
               existing_type=sa.BOOLEAN(),
               comment='True if evidence is original research, government data, or official report',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('check', 'api_coverage_percentage',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.drop_column('check', 'article_excerpt')
    # ### end Alembic commands ###