"""add_factcheck_parser_fields_to_evidence

Revision ID: c165e729198b
Revises: add_source_date_claim
Create Date: 2025-12-01 13:14:40.419986+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c165e729198b'
down_revision: Union[str, None] = 'add_source_date_claim'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fact-check parser fields (supports semantic similarity filtering)
    op.add_column('evidence', sa.Column('factcheck_target_claim', sa.String(), nullable=True))
    op.add_column('evidence', sa.Column('factcheck_claim_similarity', sa.Float(), nullable=True))
    op.add_column('evidence', sa.Column('factcheck_parse_success', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('evidence', sa.Column('factcheck_low_relevance', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'factcheck_low_relevance')
    op.drop_column('evidence', 'factcheck_parse_success')
    op.drop_column('evidence', 'factcheck_claim_similarity')
    op.drop_column('evidence', 'factcheck_target_claim')
    op.alter_column('claim', 'source_date',
               existing_type=sa.VARCHAR(),
               comment='Publication date of source article',
               existing_nullable=True)
    # ### end Alembic commands ###