"""Add rhetorical context fields to Claim model

Revision ID: 10d573b15217
Revises: 3b1a54dd6aa1
Create Date: 2025-12-16 16:01:25.467167+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10d573b15217'
down_revision: Union[str, None] = '3b1a54dd6aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('check', 'article_classification_confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('claim', sa.Column('rhetorical_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('claim', sa.Column('has_rhetorical_context', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('claim', sa.Column('rhetorical_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('rawevidence_check_id_fkey', 'rawevidence', type_='foreignkey')
    op.create_foreign_key(None, 'rawevidence', 'check', ['check_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rawevidence', type_='foreignkey')
    op.create_foreign_key('rawevidence_check_id_fkey', 'rawevidence', 'check', ['check_id'], ['id'], ondelete='CASCADE')
    op.drop_column('claim', 'rhetorical_style')
    op.drop_column('claim', 'has_rhetorical_context')
    op.drop_column('claim', 'rhetorical_context')
    op.alter_column('check', 'article_classification_confidence',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###