"""Add judge_input_hash to Claim

Revision ID: a280a370fa15
Revises: 10d573b15217
Create Date: 2026-02-09 13:40:17.538415+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a280a370fa15'
down_revision: Union[str, None] = '10d573b15217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('judge_input_hash', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'judge_input_hash')
    # ### end Alembic commands ###