#!/usr/bin/env bash
# =============================================================================
# Tru8 — Stripe Product & Price Setup
#
# Creates the 5 Stripe products + prices in test mode that mirror production.
# Run once per Stripe account (test or live). Outputs env vars to paste into
# backend/.env and web/.env.local.
#
# Prerequisites:
#   1. Install Stripe CLI: https://docs.stripe.com/stripe-cli
#   2. Login: stripe login
#
# Usage:
#   bash scripts/stripe-setup.sh            # interactive — prints env block
#   bash scripts/stripe-setup.sh --write    # appends to backend/.env
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------

if ! command -v stripe &>/dev/null; then
  echo "ERROR: Stripe CLI not found. Install it first:"
  echo "  https://docs.stripe.com/stripe-cli"
  exit 1
fi

# Quick auth check — list one product to verify login
if ! stripe products list --limit 1 &>/dev/null; then
  echo "ERROR: Stripe CLI not authenticated. Run: stripe login"
  exit 1
fi

echo "Stripe CLI authenticated. Creating products and prices..."
echo ""

# ---------------------------------------------------------------------------
# Helper: create product + price, return price ID
# ---------------------------------------------------------------------------
create_product_and_price() {
  local name="$1"
  local description="$2"
  local amount="$3"       # in smallest currency unit (pence for GBP)
  local currency="$4"
  local recurring="$5"    # "month" or "" for one-time

  # Create product
  local product_id
  product_id=$(stripe products create \
    --name "$name" \
    --description "$description" \
    -d "metadata[created_by]=tru8-setup-script" \
    --format json 2>/dev/null | grep -o '"id": "[^"]*"' | head -1 | cut -d'"' -f4)

  if [ -z "$product_id" ]; then
    echo "ERROR: Failed to create product: $name" >&2
    exit 1
  fi

  # Create price
  local price_id
  if [ -n "$recurring" ]; then
    price_id=$(stripe prices create \
      --product "$product_id" \
      --unit-amount "$amount" \
      --currency "$currency" \
      -d "recurring[interval]=$recurring" \
      --nickname "$name" \
      --format json 2>/dev/null | grep -o '"id": "[^"]*"' | head -1 | cut -d'"' -f4)
  else
    price_id=$(stripe prices create \
      --product "$product_id" \
      --unit-amount "$amount" \
      --currency "$currency" \
      --nickname "$name" \
      --format json 2>/dev/null | grep -o '"id": "[^"]*"' | head -1 | cut -d'"' -f4)
  fi

  if [ -z "$price_id" ]; then
    echo "ERROR: Failed to create price for: $name" >&2
    exit 1
  fi

  echo "  Created: $name -> $price_id" >&2
  echo "$price_id"
}

# ---------------------------------------------------------------------------
# Create products + prices
# ---------------------------------------------------------------------------

echo "--- Subscription Products (GBP, recurring monthly) ---"

PRICE_PRO=$(create_product_and_price \
  "Tru8 Starter" \
  "40 evidence checks per month" \
  700 gbp month)

PRICE_DEVELOPER=$(create_product_and_price \
  "Tru8 Professional" \
  "200 evidence checks per month" \
  2900 gbp month)

echo ""
echo "--- Credit Pack Products (GBP, one-time) ---"

PRICE_CREDIT_20=$(create_product_and_price \
  "Tru8 Credits — 20 Pack" \
  "20 evidence research credits (15p each)" \
  300 gbp "")

PRICE_CREDIT_100=$(create_product_and_price \
  "Tru8 Credits — 100 Pack" \
  "100 evidence research credits (15p each)" \
  1500 gbp "")

# ---------------------------------------------------------------------------
# Get the API keys for reference
# ---------------------------------------------------------------------------

echo ""
echo "==========================================================================="
echo "Setup complete. Add these to your environment files:"
echo "==========================================================================="
echo ""

ENV_BLOCK="# ---------- Stripe (generated by scripts/stripe-setup.sh) ----------
STRIPE_PRICE_ID_PRO=${PRICE_PRO}
STRIPE_PRICE_ID_DEVELOPER=${PRICE_DEVELOPER}
STRIPE_PRICE_ID_CREDIT_PACK_20=${PRICE_CREDIT_20}
STRIPE_PRICE_ID_CREDIT_PACK_100=${PRICE_CREDIT_100}"

echo "$ENV_BLOCK"
echo ""
echo "# Frontend (web/.env.local):"
echo "NEXT_PUBLIC_STRIPE_PRICE_ID_PRO=${PRICE_PRO}"
echo "NEXT_PUBLIC_STRIPE_PRICE_ID_DEVELOPER=${PRICE_DEVELOPER}"
echo ""

# ---------------------------------------------------------------------------
# Optionally write to backend/.env
# ---------------------------------------------------------------------------

if [ "${1:-}" = "--write" ]; then
  BACKEND_ENV="$(dirname "$0")/../backend/.env"
  if [ -f "$BACKEND_ENV" ]; then
    echo "" >> "$BACKEND_ENV"
    echo "$ENV_BLOCK" >> "$BACKEND_ENV"
    echo "Appended to $BACKEND_ENV"
  else
    echo "WARNING: $BACKEND_ENV not found. Create it from .env.example first."
  fi
fi

echo ""
echo "Next steps:"
echo "  1. Set STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET in backend/.env"
echo "  2. Set NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY in web/.env.local"
echo "  3. Run: stripe listen --forward-to localhost:8000/api/v1/payments/webhook"
echo "  4. Copy the webhook signing secret to STRIPE_WEBHOOK_SECRET"
echo "  5. Set SUBSCRIPTIONS_ENABLED=true when ready"
